# Generated by Django 3.2.12 on 2022-03-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('projects', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node',
            new_name='Note',
        ),
    ]
